import { mutation } from "./_generated/server";

export const initData = mutation({
  args: {},
  handler: async (ctx) => {
    const bikes = await ctx.db.query("bikes").collect();
    let bikesSeeded = 0;
    if (bikes.length === 0) {
      const initialBikes = [
        {
          id: "misi-beat",
          make: "Honda",
          model: "BeAT eSP",
          year: 2023,
          category: "Matic Harian",
          area: "Stasiun Bandung & Pasteur",
          platNomor: "D 2841 MSN",
          dailyRate: 85000,
          status: "TERSEDIA",
          engineDisplacement: "110 cc eSP",
          fuelConsumption: "60.6 km/l",
          transmission: "Otomatis",
          unitCondition: "Prima & Bersih",
          description: "Skutik terlaris dan paling lincah di Bandung. Sangat hemat bahan bakar.",
          image: "/img/beat.jpg",
        },
        {
          id: "misi-scoopy",
          make: "Honda",
          model: "Scoopy Prestige",
          year: 2024,
          category: "Matic Harian",
          area: "Dago & Braga Heritage",
          platNomor: "D 4912 MSN",
          dailyRate: 95000,
          status: "DISEWA",
          engineDisplacement: "110 cc Smart Key",
          fuelConsumption: "59 km/l",
          transmission: "Otomatis",
          unitCondition: "Favorit Wisatawan",
          description: "Desain retro fashionable yang sangat digemari muda-mudi Bandung.",
          image: "/img/scoppy.jpg",
        },
        {
          id: "misi-vario",
          make: "Honda",
          model: "Vario 125 CBS ISS",
          year: 2023,
          category: "Matic Harian",
          area: "Stasiun Whoosh & Padalarang",
          platNomor: "D 3381 MSN",
          dailyRate: 110000,
          status: "TERSEDIA",
          engineDisplacement: "125 cc eSP",
          fuelConsumption: "51.7 km/l",
          transmission: "Otomatis",
          unitCondition: "Tanggap & Bertenaga",
          description: "Skutik serbaguna dengan bagasi luas helm-in dan tenaga mantap.",
          image: "/img/vari.jpg",
        },
        {
          id: "misi-aerox",
          make: "Yamaha",
          model: "Aerox 155 Connected",
          year: 2024,
          category: "Maxi Scooter",
          area: "Lembang & Bandung Utara",
          platNomor: "D 5109 MSN",
          dailyRate: 135000,
          status: "TERSEDIA",
          engineDisplacement: "155 cc VVA",
          fuelConsumption: "45 km/l",
          transmission: "Otomatis",
          unitCondition: "Sporty & Kencang",
          description: "Maxi scooter sporty bertenaga 155cc VVA, sangat tangguh melibas tanjakan Lembang.",
          image: "/img/aerox.jpg",
        },
        {
          id: "misi-nmax",
          make: "Yamaha",
          model: "NMAX 155 Connected",
          year: 2024,
          category: "Maxi Scooter",
          area: "Ciwidey & Garasi Pasirkaliki",
          platNomor: "D 6042 MSN",
          dailyRate: 140000,
          status: "TERSEDIA",
          engineDisplacement: "155 cc VVA ABS",
          fuelConsumption: "43 km/l",
          transmission: "Otomatis",
          unitCondition: "Mewah & Sangat Nyaman",
          description: "Kenyamanan berkendara touring terbaik untuk perjalanan jauh rute Ciwidey atau Pangalengan.",
          image: "/img/nmax.jpg",
        },
      ];
      for (const b of initialBikes) {
        await ctx.db.insert("bikes", b);
      }
      bikesSeeded = initialBikes.length;
    }

    const bookings = await ctx.db.query("bookings").collect();
    let bookingsSeeded = 0;
    if (bookings.length === 0) {
      const initialBookings = [
        {
          bookingCode: "MSN-0001",
          customerName: "Andi Pratama",
          customerPhone: "08122334455",
          bikeId: "misi-scoopy",
          bikeName: "Honda Scoopy Prestige",
          startDate: "2026-09-11",
          rentalDays: 3,
          pickupLocation: "Stasiun Bandung (Pintu Utara)",
          pickupAddress: "Jl. Kebon Kawung No. 43",
          extraHelm: 1,
          dailyRate: 95000,
          totalAmount: 285000,
          paymentStatus: "LUNAS",
          status: "DELIVERED",
          notes: "Tamu dinas pemda Bandung, antar tepat waktu pukul 08:00 WIB",
          createdAt: "2026-09-10 14:20:00",
          updatedAt: "2026-09-11 08:15:00",
        },
        {
          bookingCode: "MSN-0002",
          customerName: "Siti Nurhaliza",
          customerPhone: "08571122334",
          bikeId: "misi-beat",
          bikeName: "Honda BeAT eSP",
          startDate: "2026-09-12",
          rentalDays: 2,
          pickupLocation: "Stasiun Whoosh Padalarang",
          pickupAddress: "Drop off area Stasiun Kereta Cepat",
          extraHelm: 0,
          dailyRate: 85000,
          totalAmount: 170000,
          paymentStatus: "DP_50",
          status: "CONFIRMED",
          notes: "Tiba dengan Whoosh jam 09.45 WIB",
          createdAt: "2026-09-11 09:10:00",
          updatedAt: "2026-09-11 09:30:00",
        },
        {
          bookingCode: "MSN-0003",
          customerName: "Budi Santoso",
          customerPhone: "08139988776",
          bikeId: "misi-nmax",
          bikeName: "Yamaha NMAX 155 Connected",
          startDate: "2026-09-13",
          rentalDays: 4,
          pickupLocation: "Hotel di Bandung",
          pickupAddress: "Hotel Savoy Homann, Jl. Asia Afrika",
          extraHelm: 1,
          dailyRate: 140000,
          totalAmount: 560000,
          paymentStatus: "BELUM_BAYAR",
          status: "PENDING",
          notes: "Perjalanan dinas ke Soreang",
          createdAt: "2026-09-11 11:45:00",
          updatedAt: "2026-09-11 11:45:00",
        },
        {
          bookingCode: "MSN-0004",
          customerName: "Rian Hidayat",
          customerPhone: "08215566778",
          bikeId: "misi-aerox",
          bikeName: "Yamaha Aerox 155 Connected",
          startDate: "2026-09-08",
          rentalDays: 2,
          pickupLocation: "Garasi Misionary (Pasirkaliki)",
          pickupAddress: "Jl. Pasirkaliki No. 88",
          extraHelm: 0,
          dailyRate: 135000,
          totalAmount: 270000,
          paymentStatus: "LUNAS",
          status: "COMPLETED",
          notes: "Unit kembali tepat waktu, kondisi sangat baik",
          createdAt: "2026-09-08 07:00:00",
          updatedAt: "2026-09-10 18:00:00",
        },
        {
          bookingCode: "MSN-0005",
          customerName: "Dinda Permata",
          customerPhone: "08198877665",
          bikeId: "misi-vario",
          bikeName: "Honda Vario 125 CBS ISS",
          startDate: "2026-09-10",
          rentalDays: 3,
          pickupLocation: "Stasiun Bandung (Pintu Selatan)",
          pickupAddress: "Jl. Stasiun Barat",
          extraHelm: 1,
          dailyRate: 110000,
          totalAmount: 330000,
          paymentStatus: "LUNAS",
          status: "DELIVERED",
          notes: "Wisata belanja & kuliner Riau",
          createdAt: "2026-09-09 16:30:00",
          updatedAt: "2026-09-10 10:00:00",
        },
      ];
      for (const b of initialBookings) {
        await ctx.db.insert("bookings", b);
      }
      bookingsSeeded = initialBookings.length;
    }

    return {
      success: true,
      message: `Inisialisasi berhasil: ${bikesSeeded} motor, ${bookingsSeeded} pesanan.`,
    };
  },
});
